#= require ./store
#= require ./local_storage
#= require_tree ./mixins
#= require_tree ./templates
#= require_tree ./helpers
#= require ./models
#= require_tree ./controllers
#= require_tree ./views
#= require_tree ./components
#= require ./routes
#= require ./router
#= require_self